/**
 * The generated `docker/` folder must match the engine sources.
 *
 * `docker/src/` is a COPY of `server/src/`, produced by
 * `server/scripts/prepare-docker.ts`. Because it is a copy rather than a
 * reference, it silently goes stale: engine fixes land, the container image
 * keeps building from the old sources, and nothing anywhere reports it. That
 * happened — the container shipped without the balance-flicker fix, the idle
 * timeout fix and the panel changes, while the local engine had all of them.
 *
 * This test compares the two trees file by file, so the drift is caught by
 * `bun test` instead of by an operator wondering why the container behaves
 * differently from the desktop build.
 *
 * It is deliberately a CONTENT comparison, not a timestamp one: a rebuild that
 * produces identical bytes is not drift, and mtimes are unreliable across a
 * git checkout.
 */
import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

/** Repo root, from this file's location: `<root>/server/src/server/`. */
const ROOT = join(import.meta.dir, "..", "..", "..");
const SRC = join(ROOT, "server", "src");
const DOCKER_SRC = join(ROOT, "docker", "src");

/** Every file under `dir`, as paths relative to it, sorted. */
function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p, base));
    else out.push(relative(base, p).replace(/\\/g, "/"));
  }
  return out.sort();
}

describe("docker/src mirrors server/src", () => {
  it("the generated folder exists", () => {
    // A missing docker/ is not a test failure by itself (the folder is
    // generated by scripts/prepare-docker.ts, and a fresh checkout that has not
    // run it has none), but it makes every check below vacuous, so say so
    // explicitly rather than passing silently.
    if (!existsSync(DOCKER_SRC)) {
      console.log("  (docker/src absent — skipping mirror checks)");
      return;
    }
    expect(existsSync(join(ROOT, "docker", "Dockerfile"))).toBe(true);
  });

  it("has exactly the same files as server/src", () => {
    if (!existsSync(DOCKER_SRC)) return;
    const want = walk(SRC);
    const have = walk(DOCKER_SRC);
    // Report both directions: a missing file means the image is stale, an extra
    // one means something was deleted upstream and the copy still carries it.
    const missing = want.filter((f) => !have.includes(f));
    const extra = have.filter((f) => !want.includes(f));
    expect({ missing, extra }).toEqual({ missing: [], extra: [] });
  });

  it("every file is byte-identical", () => {
    if (!existsSync(DOCKER_SRC)) return;
    const differing: string[] = [];
    for (const f of walk(SRC)) {
      const a = join(SRC, f);
      const b = join(DOCKER_SRC, f);
      if (!existsSync(b)) continue; // reported by the previous test
      if (!readFileSync(a).equals(readFileSync(b))) differing.push(f);
    }
    expect(differing).toEqual([]);
  });

  it("the container build inputs are present", () => {
    // Without these the image cannot build at all, and the failure would only
    // appear on a machine that has Docker.
    if (!existsSync(DOCKER_SRC)) return;
    for (const f of ["package.json", "bun.lock", "bunfig.toml", "Dockerfile", "docker-compose.yml"]) {
      expect(existsSync(join(ROOT, "docker", f))).toBe(true);
    }
  });

  it("the manual travels with the folder", () => {
    // docker/ is handed to people as a folder — copied to a Docker host, or
    // packed and sent. Whoever receives it has no README beside it, so the
    // folder has to carry its own. It is listed in prepare-docker's FILES for
    // that reason; a manual copy into docker/ would not survive a rebuild.
    if (!existsSync(DOCKER_SRC)) return;
    const manual = join(ROOT, "docker", "README.md");
    const source = join(ROOT, "README.md");
    // The clean copy has no .md anywhere, so there is nothing to carry.
    if (!existsSync(source)) return;
    expect(existsSync(manual)).toBe(true);
    // Same bytes, or the shipped manual describes a different build.
    expect(readFileSync(manual, "utf-8")).toBe(readFileSync(source, "utf-8"));
  });

  it("every file bunfig.toml names is actually in the folder", () => {
    // bunfig.toml's `[test] preload` points at ./test-preload.ts. Copying the
    // config without the file it references left `bun test` inside docker/
    // failing with "preload not found" — and that file is a safety net (it
    // redirects the state directory so no test touches a real account pool), so
    // losing it silently was worse than the visible error. The image build never
    // runs tests, which is why nothing caught it.
    if (!existsSync(DOCKER_SRC)) return;
    const bunfigPath = join(ROOT, "docker", "bunfig.toml");
    if (!existsSync(bunfigPath)) return;
    const text = readFileSync(bunfigPath, "utf-8");
    const preloads = [...text.matchAll(/preload\s*=\s*\[([^\]]*)\]/g)]
      .flatMap((m) => [...m[1]!.matchAll(/"([^"]+)"/g)].map((x) => x[1]!));
    expect(preloads.length).toBeGreaterThan(0);
    for (const rel of preloads) {
      expect(existsSync(join(ROOT, "docker", rel.replace(/^\.\//, "")))).toBe(true);
    }
  });

  it("no credential-bearing file leaked into the build context", () => {
    // A config.yaml here would be baked into the image AND would make the
    // container ignore the config compose mounts over /app/config.
    if (!existsSync(DOCKER_SRC)) return;
    const leaked = walk(DOCKER_SRC).filter((f) => /(^|\/)config\.(ya?ml|local\.ya?ml)$/i.test(f));
    expect(leaked).toEqual([]);
  });

  it("the build inputs are not excluded from the repository", () => {
    // The bug this locks down: `.gitignore` carried a bare `docker/` rule, so
    // every generated file — package.json, bun.lock, bunfig.toml, src/,
    // test-preload.ts, logo.svg — was excluded. A clone came back with only
    // Dockerfile and docker-compose.yml, and `docker compose up -d` could not
    // build, while the README called docker/ self-contained. The rule was meant
    // for the container's RUNTIME state (data/, config/), which shares the
    // folder.
    //
    // Needs git and a repository; the clean copy ships neither.
    if (!existsSync(join(ROOT, ".git"))) return;

    // One `git check-ignore` per group, not per path: seven spawns took over
    // 5s and tripped the test timeout.
    const ignoredAmong = (paths: string[]): string[] => {
      const r = Bun.spawnSync(["git", "check-ignore", ...paths], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });
      return r.stdout.toString().split("\n").map((s) => s.trim()).filter(Boolean);
    };

    const inputs = ["docker/package.json", "docker/bun.lock", "docker/bunfig.toml",
      "docker/src/index.ts", "docker/test-preload.ts"];
    expect(ignoredAmong(inputs)).toEqual([]);

    // And the runtime state must still be excluded — an over-broad fix that
    // un-ignored everything would commit an encrypted account store.
    const runtime = ["docker/data/accounts.json", "docker/config/config.yaml"];
    expect(ignoredAmong(runtime).sort()).toEqual([...runtime].sort());
  }, 20_000); // spawning git on Windows costs ~3s per call; the default 5s is close
});
